[workspace]
resolver = "2"
members = [
  "crates/audio-system",
  "crates/common",
  "crates/frontend",
  "src-tauri",
]

[workspace.dependencies]
audio-system = { path = "crates/audio-system" }
common = { path = "crates/common" }
console_error_panic_hook = "0.1.7"
fastrand = "2.3.0"
fundsp = { version = "0.23", default-features = false, features = ["std"] }
insta = "1.46.0"
js-sys = "0.3"
log = "0.4"
mint = { version = "0.5.9", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = { version = "0.27.2", features = ["derive"] }
tauri = { version = "2", features = ["rustls-tls"] }
thiserror = "2.0.17"
wasm-bindgen = "0.2.106"
wasm-bindgen-futures = "0.4.56"
web-sys = "0.3"
