[workspace]
resolver = "2"
members = [
  "crates/audio-system",
  "crates/backend",
  "crates/common",
  "crates/frontend",
]

[workspace.dependencies]
audio-system = { path = "crates/audio-system" }
common = { path = "crates/common" }
fastrand = "2.3.0"
fundsp = "0.20"
leptos_router = { version = "0.8", features = ["nightly"] }
log = "0.4"
mint = { version = "0.5.9", features = ["serde"] }
ringbuf = "0.4.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = { version = "0.27.2", features = ["derive"] }
tauri = { version = "2" }
thiserror = "2.0.16"
