[package]
name = "red-siren"
version = "0.1.0"
authors = ["a.nvlkv <a.nvlkv@protonmail.ch>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

dioxus-fullstack = { version = "0.4" }

dioxus = { version = "0.4" }
serde = { version = "1.0.159", features = ["derive"] }

# Debug
log = "0.4.19"
dioxus-logger = "0.4.1"

[features]
default = []

ssr = ["dioxus-fullstack/axum"]

web = ["dioxus-fullstack/web"]

