[build]
target = "./index.html"

[watch]
ignore = ["./crates/backend", "./crates/audio-system"]

[serve]
port = 1420
open = false

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = [
  "-c",
  "cp splashscreen.html \"$TRUNK_STAGING_DIR/splashscreen.html\"",
]
