[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = { workspace = true }
leptos = { version = "0.8.19", features = ["csr", "nightly"] }
leptos_router = { version = "0.8.13", features = ["nightly"] }
leptos_styling = { version = "0.3.1", features = ["csr"] }
