// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChamberInfo = { resolution: number, is_left_channel: boolean, wheel: Array<number>, window_size: number, };
