// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceData = { host_id: string, device_id: string, device_name: string, device_manufacturer: string | null, supports_input: boolean, supports_output: boolean, };
