// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaybackQualityGate } from "./PlaybackQualityGate";

export type PlaybackQuality = { "Auto": PlaybackQualityGate } | "LoFi" | "Medium" | "HiFi" | "Ultra";
