name: RedSiren
projectReferences:
  app_core:
    path: ../app_core/app_core.xcodeproj
packages:
  CoreTypes:
    path: ../typegen/generated/swift/CoreTypes
options:
  bundleIdPrefix: com.anvlkv.redsiren
targets:
  RedSiren:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - RedSiren
      - path: ../app_core/src/app_core.udl
        buildPhase: sources
    dependencies:
      - target: app_core/bindgen-bin
      - target: app_core/app_core-staticlib
      - package: CoreTypes
    info:
      path: RedSiren/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen: {}
    settings:
      OTHER_LDFLAGS: [-w]
      SWIFT_OBJC_BRIDGING_HEADER: generated/app_coreFFI.h
      ENABLE_USER_SCRIPT_SANDBOXING: NO
    buildRules:
      - name: Generate FFI
        filePattern: "*.udl"
        script: |
          #!/bin/bash
          set -e

          # Skip during indexing phase in XCode 13+
          if [ "$ACTION" == "indexbuild" ]; then
            echo "Not building *.udl files during indexing."
            exit 0
          fi

          # Skip for preview builds
          if [ "$ENABLE_PREVIEWS" = "YES" ]; then
            echo "Not building *.udl files during preview builds."
            exit 0
          fi

          cd "${INPUT_FILE_DIR}/.."
          "${BUILD_DIR}/debug/bindgen" generate "src/${INPUT_FILE_NAME}" --language swift --out-dir "${PROJECT_DIR}/generated"
        outputFiles:
          - $(PROJECT_DIR)/generated/$(INPUT_FILE_BASE).swift
          - $(PROJECT_DIR)/generated/$(INPUT_FILE_BASE)FFI.h
        runOncePerArchitecture: false
