[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
const-primes = "0.10.5"
log.workspace = true
mint = { workspace = true }
nalgebra = { workspace = true }
num-complex = "0.4.6"
serde = { workspace = true }
serde_json = { workspace = true }
smallvec = "1.15.1"
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
eframe = "0.33"
insta = { workspace = true, features = ["json", "redactions"] }

[[example]]
name = "node_egui"
path = "examples/node_egui.rs"

[[example]]
name = "segment_egui"
path = "examples/segment_egui.rs"

[features]
test-util = []