[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
const-primes = "0.10.5"
log.workspace = true
mint = { workspace = true }
num-complex = "0.4.6"
serde = { workspace = true }
serde_json = { workspace = true }
smallvec = "1.15.1"
strum = { workspace = true, features = ["derive"] }
tauri = { workspace = true, optional = true }
thiserror = { workspace = true }

[dev-dependencies]
insta = { workspace = true, features = ["json", "redactions"] }

[features]
tauri = ["dep:tauri"]
test = []
