[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
const-primes = "0.10.5"
eframe = { workspace = true, optional = true }
egui = { workspace = true, optional = true }
enum2egui = { workspace = true, optional = true }
env_logger = { version = "0.11", optional = true }
fastrand = { workspace = true }
log.workspace = true
mint = { workspace = true }
nalgebra = { workspace = true }
num-complex = "0.4.6"
serde = { workspace = true }
serde_json = { workspace = true }
smallvec = "1.15.1"
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
typify = "0.6.2"

[dev-dependencies]
insta = { workspace = true, features = ["json", "redactions"] }

[[example]]
name = "node_egui"
path = "examples/node_egui.rs"
required-features = ["egui"]

[[example]]
name = "segment_egui"
path = "examples/segment_egui.rs"
required-features = ["egui"]

[[example]]
name = "revolution_body_egui"
path = "examples/revolution_body_egui.rs"
required-features = ["egui"]

[[example]]
name = "thick_revolution_body_egui"
path = "examples/thick_revolution_body_egui.rs"
required-features = ["egui"]

[features]
egui = ["dep:eframe", "dep:egui", "dep:env_logger", "dep:enum2egui"]
test-util = []
