// Auto-generated by you. Do not edit.
use std::env;
use std::fs::File;
use std::io::Write;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    generate_instrument_config_consts_file().expect("Failed to generate consts");
}

fn generate_instrument_config_consts_file() -> Result<(), Box<dyn std::error::Error>> {
    // Frequency bounds
    const MIN_FREQ_HZ: f64 = 20.0;
    const SOFT_MIN_FREQ_HZ: f64 = 60.0;
    const SOFT_MAX_FREQ_HZ: f64 = 14_000.0;
    const MAX_FREQ_HZ: f64 = 20_000.0;

    // Volume bounds
    const MAX_DBS: usize = 70;

    // Inspiring values
    /// `#e30022`
    /// Crimson Red
    ///
    /// Wave length in nanometers
    pub const CRIMSON_RED_WAVE_LENGTH_NM: f64 = 664.1;
    /// `#e44d2e`
    /// Cinnabar
    ///
    /// Wave length in nanometers
    pub const CINNABAR_RED_WAVE_LENGTH_NM: f64 = 659.5;
    /// Speed of light in m/s
    const SPEED_OF_LIGHT_M_S: f64 = 299_792_458.0;
    /// Speed of sound in m/s (nominal)
    const SPEED_OF_SOUND_M_S: f64 = 340.29;
    /// Visible light spectrum min  in nanometers
    const VISIBLE_LIGHT_MIN_NM: f64 = 380.0;
    /// Visible light spectrum max in nanometers
    const VISIBLE_LIGHT_MAX_NM: f64 = 750.0;

    // Representative sound wavelength to convert frequency -> wavespeed
    // (1 meter gives v = f_sound * 1.0 which keeps numbers in plausible range)
    const REPRESENTATIVE_SOUND_WAVELENGTH_M: f64 = 1.0;

    // compute wavespeed using logarithmic scaling described above
    let compute_wavespeed = |color_nm: f64| -> f64 {
        // Convert nm -> meters
        let lambda_light_m = color_nm * 1e-9;

        // light frequency (Hz)
        let f_light = (SPEED_OF_LIGHT_M_S) / lambda_light_m;
        let log_f_light = f_light.ln();

        // compute visible spectrum log-frequency bounds
        // note: visible max nm -> smallest frequency (lowest f), visible min nm -> highest f
        let min_visible_freq = (SPEED_OF_LIGHT_M_S) / (VISIBLE_LIGHT_MAX_NM * 1e-9);
        let max_visible_freq = (SPEED_OF_LIGHT_M_S) / (VISIBLE_LIGHT_MIN_NM * 1e-9);
        let min_log_f_light = min_visible_freq.ln();
        let max_log_f_light = max_visible_freq.ln();

        // avoid division by zero (shouldn't happen for valid visible range)
        let denom = max_log_f_light - min_log_f_light;
        let normalized = if denom.abs() < f64::EPSILON {
            0.5
        } else {
            (log_f_light - min_log_f_light) / denom
        };
        // clamp 0..1
        let normalized = normalized.clamp(0.0, 1.0);

        // audible log-frequency bounds
        let min_log_f_sound = MIN_FREQ_HZ.ln();
        let max_log_f_sound = MAX_FREQ_HZ.ln();

        // map to audible log-frequency
        let log_f_sound = min_log_f_sound + normalized * (max_log_f_sound - min_log_f_sound);
        let f_sound = log_f_sound.exp();

        // choose representative sound wavelength and compute v = f * lambda
        f_sound * REPRESENTATIVE_SOUND_WAVELENGTH_M
    };

    let crimson_ws = compute_wavespeed(CRIMSON_RED_WAVE_LENGTH_NM);
    let cinnabar_ws = compute_wavespeed(CINNABAR_RED_WAVE_LENGTH_NM);

    // Get the output directory
    let out_dir = env::var_os("OUT_DIR").ok_or("No OUT_DIR")?;
    let dest_path = Path::new(&out_dir).join("instrument_constants_gen.rs");

    // Generate the constants file
    let mut f = File::create(&dest_path)?;

    writeln!(f, "// Auto-generated constants from build.rs")?;
    writeln!(f, "pub const MIN_FREQ_HZ: f64 = {MIN_FREQ_HZ:?};")?;
    writeln!(f, "pub const SOFT_MIN_FREQ_HZ: f64 = {SOFT_MIN_FREQ_HZ:?};")?;
    writeln!(f, "pub const SOFT_MAX_FREQ_HZ: f64 = {SOFT_MAX_FREQ_HZ:?};")?;
    writeln!(f, "pub const MAX_FREQ_HZ: f64 = {MAX_FREQ_HZ:?};")?;
    writeln!(f, "pub const MAX_DBS: usize = {MAX_DBS:?};")?;

    writeln!(
        f,
        "// Red color wavelengths (nm)\n\
         pub const CRIMSON_RED_WAVE_LENGTH_NM: f64 = {crimson_nm:?};\n\
         pub const CINNABAR_RED_WAVE_LENGTH_NM: f64 = {cinnabar_nm:?};",
        crimson_nm = CRIMSON_RED_WAVE_LENGTH_NM,
        cinnabar_nm = CINNABAR_RED_WAVE_LENGTH_NM
    )?;

    writeln!(
        f,
        "pub const SPEED_OF_LIGHT_M_S: f64 = {speed_of_light:?};",
        speed_of_light = SPEED_OF_LIGHT_M_S
    )?;
    writeln!(
        f,
        "pub const SPEED_OF_SOUND_M_S: f64 = {speed_of_sound:?};",
        speed_of_sound = SPEED_OF_SOUND_M_S
    )?;
    writeln!(
        f,
        "pub const VISIBLE_LIGHT_MIN_NM: f64 = {min_vis:?};",
        min_vis = VISIBLE_LIGHT_MIN_NM
    )?;
    writeln!(
        f,
        "pub const VISIBLE_LIGHT_MAX_NM: f64 = {max_vis:?};",
        max_vis = VISIBLE_LIGHT_MAX_NM
    )?;

    // Write the computed wavespeeds (f64)
    writeln!(
        f,
        "// Logarithmically mapped audible wavespeeds (m/s) derived from red wavelengths\n\
         pub const CRIMSON_RED_WAVESPEED: f64 = {crimson_ws:?};",
    )?;

    writeln!(
        f,
        "pub const CINNABAR_RED_WAVESPEED: f64 = {cinnabar_ws:?};",
    )?;

    Ok(())
}
