[package]
name = "audio-system"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
cpal = { version = "0.17.3", features = ["custom"] }
dasp_sample = "0.11.0"
dyn-clone = "1.0.20"
eframe = { workspace = true, optional = true }
egui = { workspace = true, optional = true }
enum2egui = { workspace = true, optional = true }
fastrand = { workspace = true }
fundsp = { workspace = true, default-features = false, features = ["std"] }
log = { workspace = true }
mint = { workspace = true }
num-complex = "0.4.6"
num-rational = "0.4.2"
ordered-float = "5.3.0"
parking_lot = "0.12"
spectrum-analyzer = "1.7.0"
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
u-num-it = "0.3.4"

[dev-dependencies]
common = { workspace = true }
insta = { workspace = true }
insta-fun = "^2.4"
test-log = "0.2"

[[example]]
name = "cpal_runtime_egui"
path = "examples/cpal_runtime_egui.rs"
required-features = ["egui"]

[[example]]
name = "node_sound_egui"
path = "examples/node_sound_egui.rs"
required-features = ["egui"]

[[example]]
name = "node_adsr_egui"
path = "examples/node_adsr_egui.rs"
required-features = ["egui"]

[[example]]
name = "metro_grid_node_egui"
path = "examples/metro_grid_node_egui.rs"
required-features = ["egui"]

[target.'cfg(target_os = "ios")'.dependencies]
objc = "0.2"

[features]
default = []
egui = ["dep:eframe", "dep:egui", "dep:enum2egui", "common/egui"]
