[package]
name = "audio-system"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
common = { workspace = true }
console_error_panic_hook = { workspace = true, optional = true }
# Runtime optional deps
fastrand = { workspace = true }
fundsp = { workspace = true }
js-sys = { workspace = true, optional = true }
log = { workspace = true }
parking_lot = "0.12"
ringbuf = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true, optional = true }
spectrum-analyzer = "1.7.0"
u-num-it = "0.3.1"
wasm-bindgen = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true }

[features]
default = ["rt_web_audio_unit"]
# Messaging runtime (deprecated)
rt_web = []
# Audio unit worklet (WASM target)
rt_web_audio_unit = [
  "dep:console_error_panic_hook",
  "dep:js-sys",
  "dep:serde",
  "dep:serde_json",
  "dep:wasm-bindgen",
  "dep:web-sys",
  "fastrand/js"
]
